"""
Realistic synthetic Oracle Recruiting data for development/testing.
"""

MOCK_REQUISITIONS = [
    {"RequisitionId": "REQ-1001", "RequisitionNumber": "JR-1001", "Title": "Senior Software Engineer", "RequisitionStatus": "Open", "Department": "Engineering", "Location": "Austin, TX", "HiringManager": "Alice Johnson", "Recruiter": "Bob Smith", "TargetStartDate": "2024-03-01", "CreationDate": "2024-01-10", "FilledDate": None, "NumberOfOpenings": 3, "NumberOfHires": 1, "JobFamily": "Technology", "WorkLocation": "Hybrid"},
    {"RequisitionId": "REQ-1002", "RequisitionNumber": "JR-1002", "Title": "Product Manager", "RequisitionStatus": "Open", "Department": "Product", "Location": "San Francisco, CA", "HiringManager": "Carol Lee", "Recruiter": "Bob Smith", "TargetStartDate": "2024-02-15", "CreationDate": "2024-01-05", "FilledDate": None, "NumberOfOpenings": 1, "NumberOfHires": 0, "JobFamily": "Product Management", "WorkLocation": "Onsite"},
    {"RequisitionId": "REQ-1003", "RequisitionNumber": "JR-1003", "Title": "Data Scientist", "RequisitionStatus": "Filled", "Department": "Analytics", "Location": "New York, NY", "HiringManager": "David Park", "Recruiter": "Emma Wilson", "TargetStartDate": "2024-02-01", "CreationDate": "2023-11-20", "FilledDate": "2024-01-28", "NumberOfOpenings": 2, "NumberOfHires": 2, "JobFamily": "Data & Analytics", "WorkLocation": "Remote"},
    {"RequisitionId": "REQ-1004", "RequisitionNumber": "JR-1004", "Title": "UX Designer", "RequisitionStatus": "Open", "Department": "Design", "Location": "Seattle, WA", "HiringManager": "Frank Garcia", "Recruiter": "Emma Wilson", "TargetStartDate": "2024-03-15", "CreationDate": "2024-01-15", "FilledDate": None, "NumberOfOpenings": 1, "NumberOfHires": 0, "JobFamily": "Design", "WorkLocation": "Hybrid"},
    {"RequisitionId": "REQ-1005", "RequisitionNumber": "JR-1005", "Title": "DevOps Engineer", "RequisitionStatus": "Open", "Department": "Engineering", "Location": "Austin, TX", "HiringManager": "Alice Johnson", "Recruiter": "Bob Smith", "TargetStartDate": "2024-03-01", "CreationDate": "2024-01-08", "FilledDate": None, "NumberOfOpenings": 2, "NumberOfHires": 0, "JobFamily": "Technology", "WorkLocation": "Remote"},
    {"RequisitionId": "REQ-1006", "RequisitionNumber": "JR-1006", "Title": "Sales Executive", "RequisitionStatus": "Filled", "Department": "Sales", "Location": "Chicago, IL", "HiringManager": "Grace Kim", "Recruiter": "Henry Brown", "TargetStartDate": "2024-01-15", "CreationDate": "2023-12-01", "FilledDate": "2024-01-10", "NumberOfOpenings": 3, "NumberOfHires": 3, "JobFamily": "Sales", "WorkLocation": "Onsite"},
    {"RequisitionId": "REQ-1007", "RequisitionNumber": "JR-1007", "Title": "Finance Analyst", "RequisitionStatus": "Canceled", "Department": "Finance", "Location": "New York, NY", "HiringManager": "Ian Taylor", "Recruiter": "Henry Brown", "TargetStartDate": "2024-02-01", "CreationDate": "2023-12-15", "FilledDate": None, "NumberOfOpenings": 1, "NumberOfHires": 0, "JobFamily": "Finance", "WorkLocation": "Onsite"},
    {"RequisitionId": "REQ-1008", "RequisitionNumber": "JR-1008", "Title": "HR Business Partner", "RequisitionStatus": "Open", "Department": "Human Resources", "Location": "Austin, TX", "HiringManager": "Julia Chen", "Recruiter": "Emma Wilson", "TargetStartDate": "2024-04-01", "CreationDate": "2024-01-20", "FilledDate": None, "NumberOfOpenings": 1, "NumberOfHires": 0, "JobFamily": "Human Resources", "WorkLocation": "Hybrid"},
    {"RequisitionId": "REQ-1009", "RequisitionNumber": "JR-1009", "Title": "Machine Learning Engineer", "RequisitionStatus": "Open", "Department": "Engineering", "Location": "San Francisco, CA", "HiringManager": "Alice Johnson", "Recruiter": "Bob Smith", "TargetStartDate": "2024-03-15", "CreationDate": "2024-01-12", "FilledDate": None, "NumberOfOpenings": 2, "NumberOfHires": 0, "JobFamily": "Technology", "WorkLocation": "Remote"},
    {"RequisitionId": "REQ-1010", "RequisitionNumber": "JR-1010", "Title": "Marketing Manager", "RequisitionStatus": "Filled", "Department": "Marketing", "Location": "New York, NY", "HiringManager": "Karen White", "Recruiter": "Henry Brown", "TargetStartDate": "2024-01-15", "CreationDate": "2023-11-01", "FilledDate": "2024-01-08", "NumberOfOpenings": 1, "NumberOfHires": 1, "JobFamily": "Marketing", "WorkLocation": "Hybrid"},
]

MOCK_APPLICATIONS = [
    # REQ-1001 Senior Software Engineer (3 openings)
    {"JobApplicationId": "APP-001", "RequisitionId": "REQ-1001", "CandidateId": "CAND-01", "CandidateName": "Liam Anderson", "Phase": "Offer", "State": "Active", "AppliedDate": "2024-01-15", "LastUpdatedDate": "2024-02-05", "Source": "LinkedIn", "Referral": False, "InterviewScore": 88, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-002", "RequisitionId": "REQ-1001", "CandidateId": "CAND-02", "CandidateName": "Mia Thompson", "Phase": "Interview", "State": "Active", "AppliedDate": "2024-01-16", "LastUpdatedDate": "2024-02-03", "Source": "Indeed", "Referral": False, "InterviewScore": 72, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-003", "RequisitionId": "REQ-1001", "CandidateId": "CAND-03", "CandidateName": "Noah Harris", "Phase": "Screening", "State": "Rejected", "AppliedDate": "2024-01-18", "LastUpdatedDate": "2024-01-25", "Source": "Company Website", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-004", "RequisitionId": "REQ-1001", "CandidateId": "CAND-04", "CandidateName": "Olivia Martin", "Phase": "Interview", "State": "Active", "AppliedDate": "2024-01-20", "LastUpdatedDate": "2024-02-04", "Source": "Employee Referral", "Referral": True, "InterviewScore": 91, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-005", "RequisitionId": "REQ-1001", "CandidateId": "CAND-05", "CandidateName": "Peter Jackson", "Phase": "Screening", "State": "Withdrawn", "AppliedDate": "2024-01-22", "LastUpdatedDate": "2024-01-30", "Source": "LinkedIn", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    # REQ-1002 Product Manager
    {"JobApplicationId": "APP-006", "RequisitionId": "REQ-1002", "CandidateId": "CAND-06", "CandidateName": "Quinn Davis", "Phase": "Offer", "State": "Active", "AppliedDate": "2024-01-08", "LastUpdatedDate": "2024-02-01", "Source": "LinkedIn", "Referral": False, "InterviewScore": 85, "OfferExtended": True, "OfferAccepted": False},
    {"JobApplicationId": "APP-007", "RequisitionId": "REQ-1002", "CandidateId": "CAND-07", "CandidateName": "Rachel Wilson", "Phase": "Interview", "State": "Active", "AppliedDate": "2024-01-10", "LastUpdatedDate": "2024-01-28", "Source": "Employee Referral", "Referral": True, "InterviewScore": 78, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-008", "RequisitionId": "REQ-1002", "CandidateId": "CAND-08", "CandidateName": "Sam Roberts", "Phase": "Screening", "State": "Rejected", "AppliedDate": "2024-01-12", "LastUpdatedDate": "2024-01-20", "Source": "Indeed", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    # REQ-1003 Data Scientist (filled)
    {"JobApplicationId": "APP-009", "RequisitionId": "REQ-1003", "CandidateId": "CAND-09", "CandidateName": "Tara Moore", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-12-01", "LastUpdatedDate": "2024-01-28", "Source": "LinkedIn", "Referral": False, "InterviewScore": 94, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-010", "RequisitionId": "REQ-1003", "CandidateId": "CAND-10", "CandidateName": "Umar Khan", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-12-05", "LastUpdatedDate": "2024-01-28", "Source": "University", "Referral": False, "InterviewScore": 89, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-011", "RequisitionId": "REQ-1003", "CandidateId": "CAND-11", "CandidateName": "Victoria Lee", "Phase": "Interview", "State": "Rejected", "AppliedDate": "2023-12-10", "LastUpdatedDate": "2024-01-15", "Source": "Employee Referral", "Referral": True, "InterviewScore": 70, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-012", "RequisitionId": "REQ-1003", "CandidateId": "CAND-12", "CandidateName": "William Scott", "Phase": "Offer", "State": "Declined", "AppliedDate": "2023-12-08", "LastUpdatedDate": "2024-01-20", "Source": "LinkedIn", "Referral": False, "InterviewScore": 87, "OfferExtended": True, "OfferAccepted": False},
    # REQ-1004 UX Designer
    {"JobApplicationId": "APP-013", "RequisitionId": "REQ-1004", "CandidateId": "CAND-13", "CandidateName": "Xia Chen", "Phase": "Interview", "State": "Active", "AppliedDate": "2024-01-18", "LastUpdatedDate": "2024-02-02", "Source": "LinkedIn", "Referral": False, "InterviewScore": 80, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-014", "RequisitionId": "REQ-1004", "CandidateId": "CAND-14", "CandidateName": "Yusuf Patel", "Phase": "Screening", "State": "Active", "AppliedDate": "2024-01-22", "LastUpdatedDate": "2024-01-26", "Source": "Indeed", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    # REQ-1005 DevOps Engineer
    {"JobApplicationId": "APP-015", "RequisitionId": "REQ-1005", "CandidateId": "CAND-15", "CandidateName": "Zoe Williams", "Phase": "Interview", "State": "Active", "AppliedDate": "2024-01-15", "LastUpdatedDate": "2024-02-01", "Source": "Employee Referral", "Referral": True, "InterviewScore": 76, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-016", "RequisitionId": "REQ-1005", "CandidateId": "CAND-16", "CandidateName": "Aaron Davis", "Phase": "Screening", "State": "Rejected", "AppliedDate": "2024-01-16", "LastUpdatedDate": "2024-01-22", "Source": "Company Website", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    # REQ-1006 Sales Executive (filled)
    {"JobApplicationId": "APP-017", "RequisitionId": "REQ-1006", "CandidateId": "CAND-17", "CandidateName": "Beth Taylor", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-12-05", "LastUpdatedDate": "2024-01-10", "Source": "Employee Referral", "Referral": True, "InterviewScore": 90, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-018", "RequisitionId": "REQ-1006", "CandidateId": "CAND-18", "CandidateName": "Carlos Mendez", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-12-08", "LastUpdatedDate": "2024-01-10", "Source": "LinkedIn", "Referral": False, "InterviewScore": 85, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-019", "RequisitionId": "REQ-1006", "CandidateId": "CAND-19", "CandidateName": "Diana Brooks", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-12-10", "LastUpdatedDate": "2024-01-10", "Source": "Indeed", "Referral": False, "InterviewScore": 82, "OfferExtended": True, "OfferAccepted": True},
    # REQ-1009 ML Engineer
    {"JobApplicationId": "APP-020", "RequisitionId": "REQ-1009", "CandidateId": "CAND-20", "CandidateName": "Ethan Brown", "Phase": "Screening", "State": "Active", "AppliedDate": "2024-01-20", "LastUpdatedDate": "2024-01-25", "Source": "University", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    {"JobApplicationId": "APP-021", "RequisitionId": "REQ-1009", "CandidateId": "CAND-01", "CandidateName": "Liam Anderson", "Phase": "Screening", "State": "Withdrawn", "AppliedDate": "2024-01-21", "LastUpdatedDate": "2024-01-23", "Source": "LinkedIn", "Referral": False, "InterviewScore": None, "OfferExtended": False, "OfferAccepted": False},
    # REQ-1010 Marketing Manager (filled)
    {"JobApplicationId": "APP-022", "RequisitionId": "REQ-1010", "CandidateId": "CAND-21", "CandidateName": "Fiona Clark", "Phase": "Hired", "State": "Hired", "AppliedDate": "2023-11-10", "LastUpdatedDate": "2024-01-08", "Source": "LinkedIn", "Referral": False, "InterviewScore": 88, "OfferExtended": True, "OfferAccepted": True},
    {"JobApplicationId": "APP-023", "RequisitionId": "REQ-1010", "CandidateId": "CAND-22", "CandidateName": "George Evans", "Phase": "Offer", "State": "Declined", "AppliedDate": "2023-11-12", "LastUpdatedDate": "2023-12-20", "Source": "Employee Referral", "Referral": True, "InterviewScore": 84, "OfferExtended": True, "OfferAccepted": False},
    {"JobApplicationId": "APP-024", "RequisitionId": "REQ-1010", "CandidateId": "CAND-23", "CandidateName": "Hannah Green", "Phase": "Interview", "State": "Rejected", "AppliedDate": "2023-11-15", "LastUpdatedDate": "2023-12-10", "Source": "Indeed", "Referral": False, "InterviewScore": 65, "OfferExtended": False, "OfferAccepted": False},
]

MOCK_CANDIDATES = [
    {"CandidateId": "CAND-01", "FirstName": "Liam", "LastName": "Anderson", "Email": "liam.anderson@email.com", "Phone": "+1-512-555-0101", "SourceMedium": "LinkedIn", "SourceType": "Job Board", "CreationDate": "2024-01-15", "LastActivityDate": "2024-02-05", "TotalApplications": 2, "Skills": "Python, Kubernetes, AWS"},
    {"CandidateId": "CAND-02", "FirstName": "Mia", "LastName": "Thompson", "Email": "mia.thompson@email.com", "Phone": "+1-415-555-0102", "SourceMedium": "Indeed", "SourceType": "Job Board", "CreationDate": "2024-01-16", "LastActivityDate": "2024-02-03", "TotalApplications": 1, "Skills": "Java, Spring, Docker"},
    {"CandidateId": "CAND-09", "FirstName": "Tara", "LastName": "Moore", "Email": "tara.moore@email.com", "Phone": "+1-212-555-0109", "SourceMedium": "LinkedIn", "SourceType": "Job Board", "CreationDate": "2023-12-01", "LastActivityDate": "2024-01-28", "TotalApplications": 1, "Skills": "Python, R, TensorFlow, SQL"},
    {"CandidateId": "CAND-10", "FirstName": "Umar", "LastName": "Khan", "Email": "umar.khan@email.com", "Phone": "+1-212-555-0110", "SourceMedium": "University", "SourceType": "Campus", "CreationDate": "2023-12-05", "LastActivityDate": "2024-01-28", "TotalApplications": 1, "Skills": "Python, Machine Learning, Statistics"},
    {"CandidateId": "CAND-17", "FirstName": "Beth", "LastName": "Taylor", "Email": "beth.taylor@email.com", "Phone": "+1-312-555-0117", "SourceMedium": "Employee Referral", "SourceType": "Referral", "CreationDate": "2023-12-05", "LastActivityDate": "2024-01-10", "TotalApplications": 1, "Skills": "Sales, CRM, Salesforce"},
    {"CandidateId": "CAND-21", "FirstName": "Fiona", "LastName": "Clark", "Email": "fiona.clark@email.com", "Phone": "+1-212-555-0121", "SourceMedium": "LinkedIn", "SourceType": "Job Board", "CreationDate": "2023-11-10", "LastActivityDate": "2024-01-08", "TotalApplications": 1, "Skills": "Marketing, SEO, Analytics, Hubspot"},
]

MOCK_OFFERS = [
    {"OfferId": "OFR-001", "JobApplicationId": "APP-001", "RequisitionId": "REQ-1001", "CandidateId": "CAND-01", "OfferStatus": "Accepted", "OfferDate": "2024-02-02", "ExpirationDate": "2024-02-09", "AcceptedDate": "2024-02-05", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 145000, "Currency": "USD"},
    {"OfferId": "OFR-002", "JobApplicationId": "APP-006", "RequisitionId": "REQ-1002", "CandidateId": "CAND-06", "OfferStatus": "Pending", "OfferDate": "2024-02-01", "ExpirationDate": "2024-02-08", "AcceptedDate": None, "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 160000, "Currency": "USD"},
    {"OfferId": "OFR-003", "JobApplicationId": "APP-009", "RequisitionId": "REQ-1003", "CandidateId": "CAND-09", "OfferStatus": "Accepted", "OfferDate": "2024-01-22", "ExpirationDate": "2024-01-29", "AcceptedDate": "2024-01-25", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 155000, "Currency": "USD"},
    {"OfferId": "OFR-004", "JobApplicationId": "APP-010", "RequisitionId": "REQ-1003", "CandidateId": "CAND-10", "OfferStatus": "Accepted", "OfferDate": "2024-01-22", "ExpirationDate": "2024-01-29", "AcceptedDate": "2024-01-26", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 140000, "Currency": "USD"},
    {"OfferId": "OFR-005", "JobApplicationId": "APP-012", "RequisitionId": "REQ-1003", "CandidateId": "CAND-12", "OfferStatus": "Declined", "OfferDate": "2024-01-15", "ExpirationDate": "2024-01-22", "AcceptedDate": None, "DeclinedDate": "2024-01-19", "DeclineReason": "Accepted competing offer", "OfferedSalary": 148000, "Currency": "USD"},
    {"OfferId": "OFR-006", "JobApplicationId": "APP-017", "RequisitionId": "REQ-1006", "CandidateId": "CAND-17", "OfferStatus": "Accepted", "OfferDate": "2024-01-05", "ExpirationDate": "2024-01-12", "AcceptedDate": "2024-01-08", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 120000, "Currency": "USD"},
    {"OfferId": "OFR-007", "JobApplicationId": "APP-018", "RequisitionId": "REQ-1006", "CandidateId": "CAND-18", "OfferStatus": "Accepted", "OfferDate": "2024-01-05", "ExpirationDate": "2024-01-12", "AcceptedDate": "2024-01-09", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 115000, "Currency": "USD"},
    {"OfferId": "OFR-008", "JobApplicationId": "APP-019", "RequisitionId": "REQ-1006", "CandidateId": "CAND-19", "OfferStatus": "Accepted", "OfferDate": "2024-01-05", "ExpirationDate": "2024-01-12", "AcceptedDate": "2024-01-10", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 118000, "Currency": "USD"},
    {"OfferId": "OFR-009", "JobApplicationId": "APP-022", "RequisitionId": "REQ-1010", "CandidateId": "CAND-21", "OfferStatus": "Accepted", "OfferDate": "2024-01-02", "ExpirationDate": "2024-01-09", "AcceptedDate": "2024-01-05", "DeclinedDate": None, "DeclineReason": None, "OfferedSalary": 130000, "Currency": "USD"},
    {"OfferId": "OFR-010", "JobApplicationId": "APP-023", "RequisitionId": "REQ-1010", "CandidateId": "CAND-22", "OfferStatus": "Declined", "OfferDate": "2023-12-18", "ExpirationDate": "2023-12-25", "AcceptedDate": None, "DeclinedDate": "2023-12-22", "DeclineReason": "Salary expectations not met", "OfferedSalary": 125000, "Currency": "USD"},
]

MOCK_INTERVIEWS = [
    {"InterviewId": "INT-001", "JobApplicationId": "APP-001", "RequisitionId": "REQ-1001", "CandidateId": "CAND-01", "InterviewType": "Technical", "ScheduledDate": "2024-01-28", "InterviewStatus": "Completed", "InterviewerName": "Alice Johnson", "Score": 88, "Feedback": "Strong technical skills, good problem solving."},
    {"InterviewId": "INT-002", "JobApplicationId": "APP-001", "RequisitionId": "REQ-1001", "CandidateId": "CAND-01", "InterviewType": "HR", "ScheduledDate": "2024-01-30", "InterviewStatus": "Completed", "InterviewerName": "Bob Smith", "Score": 90, "Feedback": "Excellent cultural fit."},
    {"InterviewId": "INT-003", "JobApplicationId": "APP-002", "RequisitionId": "REQ-1001", "CandidateId": "CAND-02", "InterviewType": "Technical", "ScheduledDate": "2024-01-29", "InterviewStatus": "Completed", "InterviewerName": "Alice Johnson", "Score": 72, "Feedback": "Needs improvement in system design."},
    {"InterviewId": "INT-004", "JobApplicationId": "APP-004", "RequisitionId": "REQ-1001", "CandidateId": "CAND-04", "InterviewType": "Technical", "ScheduledDate": "2024-02-01", "InterviewStatus": "Completed", "InterviewerName": "Alice Johnson", "Score": 91, "Feedback": "Outstanding candidate, top performer."},
    {"InterviewId": "INT-005", "JobApplicationId": "APP-004", "RequisitionId": "REQ-1001", "CandidateId": "CAND-04", "InterviewType": "Panel", "ScheduledDate": "2024-02-04", "InterviewStatus": "Scheduled", "InterviewerName": "Engineering Team", "Score": None, "Feedback": None},
    {"InterviewId": "INT-006", "JobApplicationId": "APP-006", "RequisitionId": "REQ-1002", "CandidateId": "CAND-06", "InterviewType": "Behavioral", "ScheduledDate": "2024-01-20", "InterviewStatus": "Completed", "InterviewerName": "Carol Lee", "Score": 85, "Feedback": "Strong PM background, good strategic thinking."},
    {"InterviewId": "INT-007", "JobApplicationId": "APP-009", "RequisitionId": "REQ-1003", "CandidateId": "CAND-09", "InterviewType": "Technical", "ScheduledDate": "2024-01-10", "InterviewStatus": "Completed", "InterviewerName": "David Park", "Score": 94, "Feedback": "Exceptional data science skills."},
    {"InterviewId": "INT-008", "JobApplicationId": "APP-010", "RequisitionId": "REQ-1003", "CandidateId": "CAND-10", "InterviewType": "Technical", "ScheduledDate": "2024-01-12", "InterviewStatus": "Completed", "InterviewerName": "David Park", "Score": 89, "Feedback": "Strong ML background from academia."},
    {"InterviewId": "INT-009", "JobApplicationId": "APP-013", "RequisitionId": "REQ-1004", "CandidateId": "CAND-13", "InterviewType": "Portfolio Review", "ScheduledDate": "2024-01-30", "InterviewStatus": "Completed", "InterviewerName": "Frank Garcia", "Score": 80, "Feedback": "Good portfolio, strong in mobile UX."},
    {"InterviewId": "INT-010", "JobApplicationId": "APP-015", "RequisitionId": "REQ-1005", "CandidateId": "CAND-15", "InterviewType": "Technical", "ScheduledDate": "2024-01-28", "InterviewStatus": "Completed", "InterviewerName": "Alice Johnson", "Score": 76, "Feedback": "Solid DevOps foundation, room for growth in cloud."},
]

MOCK_SOURCES = [
    {"SourceId": "SRC-01", "SourceName": "LinkedIn", "SourceType": "Job Board", "SourceMedium": "Digital", "ApplicationCount": 10, "HireCount": 4, "CostPerHire": 1200},
    {"SourceId": "SRC-02", "SourceName": "Indeed", "SourceType": "Job Board", "SourceMedium": "Digital", "ApplicationCount": 6, "HireCount": 2, "CostPerHire": 800},
    {"SourceId": "SRC-03", "SourceName": "Employee Referral", "SourceType": "Referral", "SourceMedium": "Internal", "ApplicationCount": 5, "HireCount": 3, "CostPerHire": 300},
    {"SourceId": "SRC-04", "SourceName": "Company Website", "SourceType": "Direct", "SourceMedium": "Digital", "ApplicationCount": 2, "HireCount": 0, "CostPerHire": 0},
    {"SourceId": "SRC-05", "SourceName": "University", "SourceType": "Campus", "SourceMedium": "Events", "ApplicationCount": 2, "HireCount": 1, "CostPerHire": 500},
]
